services:
  - type: web
    name: weathersmart-ai-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --bind 0.0.0.0:$PORT
    envVars:
      - key: WEATHER_API_KEY
        sync: false
      - key: FLASK_DEBUG
        value: false
      - key: PORT
        value: 10000
      - key: EMAIL_SENDER
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_FROM_NUMBER
        sync: false
